GenericPositionSyncEvent=0
GenericPositionSyncEvent=0
PlayerSpawnEvent=1
PlayerDespawnEvent=2
PlayerMoveEvent=3
SyncShipPositionEvent=4
SyncShipBlocksEvent=5
SyncShipEvent=6
BlockUpdateEvent=7
BlockRemoveEvent=8
EnterShipEvent=9
Test=10
LoadShipEvent=11
TryEnterShipEvent=12
E=13
En=14
Ent=15
Ente=16
Enter=17
Entere=18
Entered=19
EnteredS=20
EnteredShg=21
EnteredShgi=22
EnteredShgip=23
EnteredShgipE=24
EnteredShgipEv=25
EnteredShgipEve=26
EnteredShgipEven=27
EnteredShgipEvent=28
EnteredSh=29
EnteredShio=30
EnteredShiop=31
EnteredShi=32
EnteredShip=33
EnteredShipE=34
EnteredShipEv=35
EnteredShipEve=36
EnteredShipEven=37
EnteredShipEvent=38
TryLeaveShipEvent=39
LeftShipEvent=40
ShipMoveEvent=41
PlayerReady=42
PlayerReadyEvent=43
UnloadShipEvent=44
