[package]
name = "spacegame_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "spaccegame_core"
path = "src/lib.rs"

[dependencies]
bevy = "*"
bevy_renet = "*"
serde = "*"
bincode = "*"
fastrand = "*"